
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://postgres:5432/chat_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8086

application:
  urls:
    user-service: http://api-gateway:8762/api/security/user
    restaurant-index: restaurants
    order-service: http://api-gateway:8762/api/order