spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      group-id: restaurantGroup
      auto-offset-reset: earliestDataSource
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#logging:
#  file:
#    name: /Users/jakubsokol/feasto-app-main/feasto-backend/logs/elk-stack.log
# application.yml
logging:
  level:
    org.springframework.boot: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

environment:
  name: LOCAL


application: # Correct indentation
  urls:
    user-service: http://localhost:8762/api/security/user
    restaurant-index: restaurants
    order-service: http://localhost:8762/api/order